esphome:
  name: esp32-ld2420
  friendly_name: esp32-ld2420

esp32:
  board: mhetesp32minikit
  framework:
    type: esp-idf

logger:

# Enable web server
# web_server:
#   port: 80
#   version: 3
#   local: true

# Enable Home Assistant API
api:
  encryption:
    # See https://esphome.io/components/api.html
    key: !secret api_key

# Enable OTA
# See https://esphome.io/components/ota/esphome.html
# ota:
#   - platform: esphome
#     password: !secret ota_password

wifi:
  # See https://esphome.io/components/wifi.html
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: "ESP32-LD2420"
  #   password: !secret wifi_fallback_password

captive_portal:

uart:
  id: ubus
  tx_pin: GPIO19
  rx_pin: GPIO23
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

ld2420:

text_sensor:
  - platform: ld2420
    fw_version:
      name: LD2420 Firmware

sensor:
  - platform: ld2420
    moving_distance:
      name : Moving Distance

binary_sensor:
  - platform: ld2420
    has_target:
      name: Presence

select:
  - platform: ld2420
    operating_mode:
      name: Operating Mode

number:
  - platform: ld2420
    presence_timeout:
      name: Detection Presence Timeout
    min_gate_distance:
      name: Detection Gate Minimum
    max_gate_distance:
      name: Detection Gate Maximum
    # See "Number" section below for detail
    gate_select:
      name: Select Gate to Set
    still_threshold:
      name: Set Still Threshold Value
    move_threshold:
      name: Set Move Threshold Value

button:
  - platform: ld2420
    apply_config:
      name: Apply Config
    factory_reset:
      name: Factory Reset
    restart_module:
      name: Restart Module
    revert_config:
      name: Undo Edits
  - platform: restart
    name: "Restart"
